### ISSUE TITLE
'template' won't be navigated for route added by javascript 

### ISSUE THREAD

**Issue by gundam78** [pinecone-router/router#33] opened 2024-02-20 03:01 UTC
**Describe the bug**
'template' won't be navigated for route added by javascript (4.2.0)

**To Reproduce**
1. window.PineconeRouter.add('/', {handlers: [], template: '/home.html'})
2. click the link '/' won't load '/home.html' page.

**Expected behavior**
link should work

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 4.2.0

**Comment by rehhouari** [comment] 2024-02-21 02:21
I can confirm this was not considered, I'm wondering how you expect this to behave?
Since there is no `x-route` element it cannot be rendered in it.

Only way this work is to add a "target" option, and show the template in that element. However the template logic is inside the `x-template` directive, I'll see if I can extract it.

**Comment by gundam78** [comment] 2024-02-21 06:39
> I can confirm this was not considered, I'm wondering how you expect this to behave? Since there is no `x-route` element it cannot be rendered in it.
> 
> Only way this work is to add a "target" option, and show the template in that element. However the template logic is inside the `x-template` directive, I'll see if I can extract it.

For some reason, I want to manage routes in js, and this worked fine for 3.x, using 'views' middleware.

```html
<a class="btn" href="/">Home</a>

<div id="app" x-data></div>
```

```javascript
document.addEventListener('alpine:initialized', () => {
    PineconeRouter.add('/', {handlers: [], view: ['/home.html']});
});
```

Recently, I upgraded to 4.x and saw changelog said: ```"x-template directive replacing the views middleware"```.  So I try to change options to ```{handlers: [], template: '/home.html'}``` according to the document and expected the same behavior.

**Comment by rehhouari** [comment] 2024-02-21 18:18
Sorry for the inconvenience, I will try to make it load the template and show it in the `window.PineconeRouter.settings.templateTargetId` element.

Note: This will mean that if the route with template is added programmatically, it will show when the route is matched, however, it will not clear automatically, this is to keep compatibility with `x-template`. so you must have a route and template for `notfound` route and every other route or otherwise when the route is changed to another that doesn't have a template, the previous template will keep showing. Is that okay?

**Comment by rehhouari** [comment] 2024-02-21 19:30
Fixed in 4.3.0.
Let me know if you find further issues and thanks for submitting this one!

**Comment by gundam78** [comment] 2024-02-22 03:58
> Note: This will mean that if the route with template is added programmatically, it will show when the route is matched, however, it will not clear automatically, this is to keep compatibility with `x-template`. so you must have a route and template for `notfound` route and every other route or otherwise when the route is changed to another that doesn't have a template, the previous template will keep showing. Is that okay?

4.3.0 fixed! It okay for my case, actually, I handle almost all 'wildcard' routes in notfound handler except some hardcode ones such as  '/'.

Thank you for the fixed and the whole extension, pinecone-router is very useful and handy, and with good interface design :)

**Closed** 2024-02-22 04:05 UTC

**Comment by rehhouari** [comment] 2024-02-22 21:10
Glad to hear it working! thanks for using it:)
